<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOfmvlts\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOfmvlts/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerOfmvlts.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerOfmvlts\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerOfmvlts\appProdProjectContainer([
    'container.build_hash' => 'Ofmvlts',
    'container.build_id' => '797eb9f8',
    'container.build_time' => 1574215020,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOfmvlts');
